### ISSUE TITLE
Automatically load Tiles, if above the Tile Providers max zoom level

### ISSUE THREAD

**Issue by eehpcm** [ChristopherGittner/OSMBugs#11]
Zoom in to the max, click on a bug to get the details.  Go back to map, either by clicking on the bug symbol at top-left (it's not intuitive that takes you back to the map) or the navbar back arror.  Either way the bugs are there but the map tiles are not.  Zoom out a couple of levels and map tiles return.

Also happens one level below max, maybe two levels below.

Related to last set of changes that allowed greater zooming?

**Comment by ChristopherGittner** [comment]
Added an Option to enable or disable the maximum zoom override, with a warning describing this behaviour.
Sadly, there is no easy way to load tiles at a zoom level greater than the Tile Providers max zoom level with the osmdroid library. So everyone, who wants to use higher zoom levels has to live with this problem for now :-(

**Comment by eehpcm** [comment]
OK, so you can't load tiles at a higher zoom level **directly**.  But if at first you don't succeed, _cheat_. :)

You ought to be able to do, programmatically, how I work around it.  I zoom out until I get tiles, then zoom back in.  OSMBugs pulls the tile at the provider's max zoom and then magnifies it. So...

You ought to able to tell that the map has been slipped in some direction and that therefore you don't have a tile.  Request it at appropriate zoom level, if the view isn't zoomed in too much.  Otherwise request it at provider's max zoom level and magnify it.  SMOP. :)

Yeah, I know, there are lots of fiddly little details to get right or it all falls over in a smelly heap.  But it's not that different from what already happens, there are just a few more details to take care of.

**Comment by ChristopherGittner** [comment]
Hi eehpcm,

this was my first intention as well. There are only 2 problems with this "hack".
- The Map will flicker if the Tiles are already in the Cache, because of zooming out first, and zooming back in afterwards. If the Tiles are not yet in the cache, the map might eventually zoom in to some location, after a delay.
- If scrolling the map, while being above the tile providers max zoom level, i would need to zoom out first, wait for all tiles to be loaded, and zoom back in, which would be no nice user experience in my opinion. Aside from the Fact that the tiles will never load in the current App version. But now the User has chosen to deal with this issue.

Anyhow, the correct solution is, to modify the osmdroid library in such a way, that it will still load the max provider tiles, even if above the maximum zoom level. But for this, i would have to dig deeper into the library, for which i currently don't really have the time.

So i will reopen this issue, as a reminder for myself :-)

**Comment by eehpcm** [comment]
Your conception of the hack appears to be a little more primitive (and hence simpler to program) than mine.  In my version a clever programmer had hidden a lot of that behind the scenes such that the internal machinations never made it to the screen.

But I can see that how easy it is to do, and how it's going to display, depends on how decomposable the APIs are.  If you feed it screen dimensions, location and zoom then it does all the rest, you're somewhat stuck.  If you're feeding it calls to "grab this tile at this resolution" and then drawing it, there's a lot more flexibility.

Here's an elegantly ugly way of doing it, if the API allows.  Have a virtual screen.  That screen never displays at more than max_zoom and uses straight API calls as you're using them now.  The centre of the virtual screen is at same geographical location as the centre of the real screen.  When I'm at overzoom factor 3, swiping the real screen left by half a screen would move the virtual screen left by 1/6 of a screen.  Co-ordinate transformation from real to virtual and magnification from virtual to real.

Something like that.  It's all simple to do when you don't understand it. :)

**Comment by ChristopherGittner** [comment]
Here's good News:

The new osmdroid version now does tile loading above the default zoomlevel automatically. So with the newest version of Osmbugs this is fixed.
