### ISSUE TITLE
why Mapdust

### ISSUE THREAD

**Issue by matkoniecz** [ChristopherGittner/OSMBugs#15]
Why on reporting problem it asking user whatever (s)he wants to use Mapdust? It is a private clone of OSM notes, basing on OSM Wiki it seems to be terrible place to send a real feedback.

What worse asking this question on submitting notes makes interface more complicated and cluttered.

**Comment by ChristopherGittner** [comment]
Maybe the interface can be restructured, so that there will be a default option, which selects the error report Platform, and a button that says, "Remember my decission" or some sort of.

Another thing to keep in mind is, that if a Platform is deselected, the user probably does not want to use this platform for reporting new bugs either...

**Comment by matkoniecz** [comment]
But: why anybody would want to use Mapdust? Is there any usecase when it would be better?

**Comment by ChristopherGittner** [comment]
This Repository is not the right place to ask the Question, wether Mapdust should be used or not.

Anyway, i added an option in the Settings, so that one can select a default platform, on which the new bug should be created. This way the Dialog won't show up if you create a new bug.
