### ISSUE TITLE
why OSM notes are last in the tab list

### ISSUE THREAD

**Issue by matkoniecz** [ChristopherGittner/OSMBugs#16]
Why OSM notes is listed as the last one on the tab view, despite being the best source of complaints? It should be more accessible or at least before Mapdust.

**Comment by ChristopherGittner** [comment]
This is just the order, they were added in the App. OSM Notes was one of the last apis, that were implemented, so it got pushed to the back.
But i am with you, that it is probably a little more relevant than mapdust, and since it is kind of the "official" reporting function for Openstreetmap, it might be a good idea, to put it to the front.

**Comment by ChristopherGittner** [comment]
Note to myself: If there is no Bug to be displayed, the category does not need to be shown.
