### ISSUE TITLE
Share function broken

### ISSUE THREAD

**Issue by Mannivu** [ChristopherGittner/OSMBugs#35]
The share function states "No App found to share the Bug with". I've installed a few OSM apps (Vespucci, OsmAnd, EveryDoor and StreetComplete) so it seems unlikely none of them is suitable.

**Comment by mnalis** [comment]
Which version of OSMBugs? 

In OSMBugs 1.4.0 from F-droid, on Android 14, clicking share button offers me (among other things) StreetComplete, OsmAnd and Vespucci.

**Comment by Mannivu** [comment]
Same version on Android 13. This is what I get
![IMG_20240524_164516](https://github.com/ChristopherGittner/OSMBugs/assets/42747216/b193047f-1e2b-420b-bde9-4ff1eaba8ce5)

**Comment by mnalis** [comment]
Interesting. Did you perhaps have some app set as default to open `geo:` intents previously?

If uninstalling and installing again OSMBugs does not help, could you install https://f-droid.org/en/packages/uk.co.ashtonbrsc.android.intentintercept/ and see if the share menu appears then?

it works normally here:
![small_Screenshot_20240524_172645_Android System](https://github.com/ChristopherGittner/OSMBugs/assets/156656/c1d8d267-b000-4858-a31b-ce284535cd3b)

**Comment by Mannivu** [comment]
I've downloaded the app you suggested and after installing it I get a prompt to select an app (great!). But if I disable the app, I get the same error. I'm quite sure I don't have any default app for the `geo:` extension but I'll check that.

**Comment by mnalis** [comment]
> I've downloaded the app you suggested and after installing it I get a prompt to select an app (great!). But if I disable the app, I get the same error

If you select `Intent Intercept` as an app to share to, can you:

- send a full screenshot (multipage) of what it shows?
- if you choose `SEND EDITED INTENT` at the bottom of `Internet Intercept` when you shared to it, does it give you a list of apps to share to?

**Comment by Mannivu** [comment]
This is what Intent interceptor shows when I select it
![Screenshot_2024-05-25-08-56-21-854_uk co ashtonbrsc android intentintercept](https://github.com/ChristopherGittner/OSMBugs/assets/42747216/d1315010-b895-48c1-bb30-16bc9a82e20c)

If I tap "Send Edited Intent" I get this
![Screenshot_2024-05-25-08-56-45-506_android-edit](https://github.com/ChristopherGittner/OSMBugs/assets/42747216/596e54e9-42f7-4600-aa1d-ce9ba84502ad)

**Comment by mnalis** [comment]
Hmm, that intent data looks the same as the one on my Android 14, where sharing works normally.

Can you try with some app from which sharing works for you (e.g. OsmAnd):

- in OsmAnd long press on location, click share button, and choose `geo:`
- does it offer all other apps here (StreetComplete, SCEE, Vespucci...) or only Intent Intercept?
- choose `Intent Intercept` app
- make another screenshot of Intent Intercept, so we can compare how working intent differs from the one sent by OSMBugs?

**Comment by Mannivu** [comment]
I've tried sharing a geo: code with Osmand after disabling Intent intercept and I get the correct share prompt
![Screenshot_2024-05-30-14-32-59-974_android](https://github.com/ChristopherGittner/OSMBugs/assets/42747216/2918ec28-62af-4cd2-8c9f-3a4e7c381db3)

This is what I get if I select Intent intercept
![Screenshot_2024-05-30-14-33-40-848_uk co ashtonbrsc android intentintercept](https://github.com/ChristopherGittner/OSMBugs/assets/42747216/a97c8b9f-7e88-4b33-9fab-9ac807640fba)

**Comment by mnalis** [comment]
Comparing working with non-working intent, only difference I see are:

- OsmAnd appends `?z=16` for zoom to that `geo:` link, while OSMbugs doesn't. However, that shouldn't matter according to the [geo: standard](https://en.wikipedia.org/wiki/Geo_URI_scheme#Unofficial_extensions) AFAICT. In fact, that `?z=16` is (while popular) unofficial extension, so if anything should have the problem, it should be OsmAnd instead
- The application sending the intent is (obviously) different, so Android OS might somehow decide to block some apps from sending intents.

You can try to eliminate the former by finding another app that sends `geo:xxx,yyy` without `?z=xxx`. If the problem also occurs there, then that is _probably_ (but not guaranteed) the source of the problem - that your android OS version has a bug relating to `geo:` handling. If however the other app works correctly and shows all apps, then it is _guaranteed_ that this is not the problem.

---

As for the latter (which I guess is more probable cause of the issue), it is much harder to debug. You can try several things, like:
- uninstalling and installing again OSMbugs
- trying `clear data` in android settings for OSMbugs (as sometimes google cloud thingy likes to reinstall old preferences for newly installed apps automagically)
- playing with various permissions / power saving / defaults Android settings for the app. Because newer androids like to "freeze" apps, auto-remove permission after some time etc, so perhaps some of that might be the cause. See https://dontkillmyapp.com/ for hints where such settings might be hidden.

Only way to be sure it's not due to some android per-app settings, would be to hard reset the phone (losing all apps and data!), and after reset, without entering any Google or Samsung/Huawei/whatever logins (to prevent cloud restoring any settings automatically) install just the few apps for test. But that is obviously highly impractical, unless the issue is on a new phone without any important apps / data, or old phone one keeps for testing purposes...

**Comment by mnalis** [comment]
> they all seem to have the z= parameter so I'm not sure how to find an app that doesn't have it when sharing.

@Mannivu neither do I, but I only use a few apps... Anyway, you can try the second part of the my post if you want to try that approach.

As for the the app, I guess it could add `?z=xxx` parameter if that is not too hard to determine current zoom factor (or even it could always just pass hardcoded e.g. `?z=18`). That way it would look similar to most other apps.

(There is also the possibility that there are different ways / compatibility levels of sending intents, but one would have to check what approach are working apps using, and if that differs from what OSMbugs is using, which is a lot of work, especially as the issue seems limited to your one phone only so far)

**Comment by Mannivu** [comment]
I've tried wit the Wikipedia geo: URI that is missing the `?z=` parameter and it worked
![Screenshot_2024-06-01-11-20-49-877_android](https://github.com/ChristopherGittner/OSMBugs/assets/42747216/a4824785-3013-4f72-881d-2621ad18f385)

I really don't know what cause this issue. I've tried clearing data, uninstalling, reinstalling both from GPlay and F-Droid but I still get the same error. I'll try uninstalling all the other apps and try to see if some of them causes the issue (I don't know if this makes sense but at this point I guess everything is worth trying).

**Comment by mnalis** [comment]
> Before starting the intent the App checks whether or not there is at least one Application that will handle the intent.

@ChristopherGittner Perhaps that check is not working correctly everywhere (maybe some security feature is denying that)? What would happen if the check was removed, i.e. if OSMbugs were to just send the intent and no application was setup to handle it? App crash, or just nothing? 

It might be preferable to check which doesn't always work correctly...

**Comment by ChristopherGittner** [comment]
Hey guys,

thanks for trying to find the root of this cause.

@mnalis This would also be my guess after all the information.

I created 3 different Versions of Osmbugs to maybe further debug this:

- zoom-10: Adds the ?z=10 parameter
- resolve-activity: Uses intent.resolveActivity(context.packageManager) to check whether or not an activity can handle the Intent
- no-check: All checks disabled. Just fire the Intent (Might crash the app)
- match-all: Replaces the PackageManager.MATCH_DEFAULT with MATCH_ALL when trying to query the Intents

@Mannivu Can you please try those versions and report the result of which one (hopefully) worked?

[osmbugs-zoom-10.zip](https://github.com/user-attachments/files/15524516/osmbugs-zoom-10.zip)
[osmbugs-resolve-activity.zip](https://github.com/user-attachments/files/15524517/osmbugs-resolve-activity.zip)
[osmbugs-no-check.zip](https://github.com/user-attachments/files/15524518/osmbugs-no-check.zip)
[osmbugs-match-all.zip](https://github.com/user-attachments/files/15524519/osmbugs-match-all.zip)

**Comment by Mannivu** [comment]
I've tried all four and the only one to work is the "no_check" version.

**Comment by ChristopherGittner** [comment]
Ok. Thanks for your help.

The new Version now just sends the Intent without a prior check. If it fails, the Exception is catched and the same Error Message is schown. Hopefully this resolves the problem for you :-)

**Comment by Mannivu** [comment]
I'll let you know as soon the apps updates itself

**Comment by Mannivu** [comment]
I've just updated the app and I can confirm the share function work again. Thanks!
